#!/bin/sh

export KF5_PREFIX=/opt/kf5
export XDG_CONFIG_DIRS=$KF5_PREFIX/etc/xdg
export XDG_DATA_DIRS=$KF5_PREFIX/share
export QT5PREFIX=/opt/qt5
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/$QT5PREFIX/lib/pkgconfig

export PATH=$PATH:/opt/qt5
