#!/bin/sh

# # # # # # # # # # # # # # # # # # # # # # # # # # 
# GLOBAL VARIABLES TO BE USED BY THE INSTALLER
# 
# DO NOT EDIT THIS FILE
# # # # # # # # # # # # # # # # # # # # # # # # # # 

FILESYSTEM=""
MOUNT_POINT="/mnt/panda-linux"
